#!/bin/bash

set -x

if [ -z "$COMMAND_LINE_INSTALL" ]; then
  echo "正在通过 GUI 安装器运行安装脚本"
else
  echo "正在通过命令行 installer 安装" > /tmp/install_debug.log
fi

# 创建必要的目录
mkdir -p /usr/local/bin
mkdir -p /Library/LaunchDaemons
mkdir -p /var/log

exit 0